### ISSUE TITLE
Proguard

### ISSUE THREAD

**Issue by dtac-watcharapon** [omise/omise-android#20]
When i set minifyEnabled is true 
Compiler return below

Warning:co.omise.android.CardIO: can't find referenced class io.card.payment.CardIOActivity
Warning:co.omise.android.ui.CreditCardActivity: can't find referenced class io.card.payment.CardIOActivity
Warning:co.omise.android.ui.CreditCardActivity: can't find referenced class io.card.payment.CreditCard 

How to fix it?

**Comment by chakrit** [comment]
@dtac-watcharapon [Card.io](https://www.card.io) is used for the camera scanning functionality. The dependency is added with `provided` scope so your application should builds fine even without Card.io support.

If you wish to use the card scanning functionality, please add the following to your `build.gradle` file in `dependencies` block:

```
compile 'io.card:android-sdk:5.4.0'
```

We will investigate ways to quench the warnings in your case but otherwise it should be safe to ignore those warnings for now.

**Comment by pitiphong-p** [comment]
Hello @dtac-watcharapon could you give us more information? We fail to try to reproduce your issue.
