### ISSUE TITLE
omise internet banking threading

### ISSUE THREAD

**Issue by j2emanue** [omise/omise-android#41]
can you research if there is a treading issue. if i test too quickly on the authorize activity  then odd time it fails. out of 10 times testing it can fail twice if i go too quickly hitting the success button produces failure at odd times. we want to put this in espresso test so we dont want it to be flaky.  Confirmed i am passing in authorize uri and return uri to the activity. it all works just sometimes it fails if i go quickly.

**Comment by chakrit** [comment]
@j2emanue Can you explain more on the failure you mention. How exactly is the app failing? Are there error messages?

**Comment by j2emanue** [comment]
its not in production. never tried yet. but in the testing authorization activity. if i hit "success" too quickly sometimes it just produces a failure.

**Comment by nuxzero** [comment]
@j2emanue Can you show your failure please?

**Comment by j2emanue** [comment]
i dont have a stack trace as i am on client.  tell me this, is there some kind of time period between failures ? i mean can i retry the same payment multiple times very quickly or is there a wait time between retrying the same payment method ?

**Comment by pitiphong-p** [comment]
When you said `mark it successful next time ` you meant on a new charge? Also do you have a video recording of your scenario? So that we can understand more clearly and correctly.

**Comment by j2emanue** [comment]
let me explain what i have narrowed down the issue to be.  after Omise sdk calls onActivityResult i call our servers to verify payment (through omise api) but sometimes the payment is marked as "pending". this is causing me to have to show the user that the transaction failed (since its not in a successful state).  why did omise sdk not wait until status is either success or failure and then call onActivityResult. this can resolve my issues.

**Comment by pitiphong-p** [comment]
We've worked together with the Internet Banking team to address your issue. Please find our response below.

Once the customer follows the authorized URL, the authorization process is handled by a 3rd party, which in this case is the bank. The customer's activity/ behavior which occurs during this stage is beyond our control. The idea of having the AuthorizingPaymentActivity is to ease the integration of 3DS and other similar services for our merchants.

Since this stage of the transaction is handled by a 3rd party, the information we receive is quite limited. We are only informed whether the customer has completed the authorization process or has chosen to cancel the operation. So in the case where "onActivityResult is getting called but the transaction is showed as pending on the Omise dashboard", this may be caused by a delay in response from the bank to Omise. In most cases, the charge will be updated within a short moment, however, may take up to 30 minutes or an hour in some cases.

I hope this helps.

**Comment by pitiphong-p** [comment]
@j2emanue Does my comment help you on your issue? And do you any more question?

**Comment by j2emanue** [comment]
please close this ticket as resolved.
