### ISSUE TITLE
minSdk is set as Android 18

### ISSUE THREAD

**Issue by jutikorn** [omise/omise-android#46]
Any a particular reason to update your Android SDK min version to Android 18?
I am currently using omise-sdk version 2.0.1 and cannot update it to 2.6.4 because my application minSdk version is set to Android 15.
Is it possible to bring your minimum support sdk down to 15?

**Comment by pitiphong-p** [comment]
We need to set minimum SDK to API 16 due to the supported encryption built in the Android OS. The minimum requirement of encryption suite is TLS 1.2 with at least SHA 256 as a minimum. Due to that the TLS 1.2 is not supported in Android version earlier than API 16 so we decided to drop support for those versions

**Comment by jutikorn** [comment]
@pitiphong-p thanks for reply, could you let me know when will you guys stop the support to  Omise SDK version 2.0.1? Since now I cannot yet update my application minimum SDK. 
Thanks.

**Comment by pitiphong-p** [comment]
We don't have any explicit plan to stop supporting our old versions of the library. However we do encourage our merchants to adopt the latest version of our library as soon as possible since there are new features, bug fixes and most importantly the security fixes come with the new version.

But I think we don't support Android API 15 or lower due to the TLS 1.2 requirement which means that you may not be able to support the those API 15 or lower versions without a hard work change in our library. I suggest you to adopt our latest SDK version and drop support for Android API 15 or lower

**Comment by chakrit** [comment]
@jutikorn @pitiphong-p We will drop support for TLS1.1 completely on our PCI-DSS vault soon (if not already done). It is a hard requirement for compliance. This means all credit card payments on old Android versions will simply stop working regardless of what SDK version you use and wether or not you upgrade.

**Comment by jutikorn** [comment]
@chakrit Thanks for reply.
 Could you clarify the exact time when will the TLS 1.1 be completely dropped? I have to plan and propose this to my client to increase up the Android minimum SDK which will impact some current users.

Thank you.

**Comment by pitiphong-p** [comment]
@jutikorn unfortunately I believe that TLS 1.1 has been already dropped support for awhile now
