### ISSUE TITLE
AppCompat support???

### ISSUE THREAD

**Issue by darienalvarez** [omise/omise-android#54]
Most of the apps now are based on APPCompat, are you going to update the library or at least add a different AppCompat Activity?

**Comment by nuxzero** [comment]
Thank you for raising this issue with us. Upgrading to AndroidX is already on our roadmap and should be included in our future versions. However, the SDK provided the UI components to help the developer create UI. Please feel free to contact us again if you have any other questions or concerns.

**Comment by nuxzero** [comment]
Since `AppCompatActivity` is a part of **AndroidX**, we need to adopt **AndroidX** to **omise-android**. However, **AndroidX** support backward-compatibility that means you can use **Appcompat** on **AndroidX**. 

In the case, you are using `CreditCardActivity` you can create your own `AppCompatActivity` with the provided UI components. But if you are using `AuthorizingPaymentActivity` you need a separate theme for this case.

However, we will make an announcement when having a new release version. 


Sorry for inconvenient.
